[experiment]

[metrics]
daily = ["opt_in_rate"]
weekly = ["opt_in_rate"]
overall = ["opt_in_rate"]

[metrics.opt_in_rate]
select_expression = """
  MAX(CAST( COALESCE(user_pref_browser_urlbar_quicksuggest_onboarding_dialog_choice,
      '') = "accept_2" AS int ))
"""
data_source = "clients_daily"
friendly_name = "Modal Opt-In Rate"
description = "Fraction of users who opted in on the modal"
[metrics.opt_in_rate.statistics.binomial]
